### ISSUE TITLE
undefined symbol: PyCObject_Type

### ISSUE THREAD

**Issue by jacobleonard545** [astrosmili/smili#4]
When loading the modules (specifically imdata) in the python interpreter, I'm getting an error message: 

```ImportError: .../smili/smili/fortlib.so: undefined symbol: PyCObject_Type```

It's possible that this is an f2py issue or rather a python vs python3 compilation issue, but I can't seem to figure out how to resolve this. I'm having difficulty finding other online resources on how to get past this problem, so anything helps.

**Comment by kazuakiyama** [comment]
Thanks for reporting this. Did you see any dynamic library of fortlib after "make"? If you don't see it, f2py may be failed for some reasons.

**Comment by jacobleonard545** [comment]
I believe I do see it. Also, the anaconda package link is missing from the documentation. Would it be possible to let me know which one you used?

**Comment by jacobleonard545** [comment]
I do see it, so I believe that's not the issue. Would it be possible to see your environment file (for pyenv and anaconda packages/dependencies)? I came across some issues with other's projects that they ran into when using these two, so that may be something to double check.

**Comment by kazuakiyama** [comment]
Interesting. I have never heard of this message previously. Most of SMILI users in the EHT work in python 3.7, based on pyenv+anaconda3 or simply conda. This may be something coming up with recent versions of numpy or python. Can you give us more details about your environment?

**Comment by jacobleonard545** [comment]
Sorry for late response, I probably should've shown you what my machine is telling me when I try to run everything to make things easier. 

I also used this conda command and activated it to use a 3.7 environment:

```conda create --name env python=3.7```

Here's the output and environment information:

```Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from smili import imdata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jacob/EAGER/smili/smili/imdata/__init__.py", line 11, in <module>
    from .imdata import *
  File "/home/jacob/EAGER/smili/smili/imdata/imdata.py", line 33, in <module>
    from .. import fortlib, util, uvdata
ImportError: /home/jacob/EAGER/smili/smili/fortlib.so: undefined symbol: PyCObject_Type
>>> 
```

**Comment by jacobleonard545** [comment]
Sorry for the late response, I haven't been able to work on it lately. It will probably be easier to show you what my machine is displaying. I suspect it could be my lack of experience with anaconda, so ill show the command im using as well.

Conda command:
```conda create --name env python=3.7 numpy pandas scipy astropy matplotlib -y```

Here's the error I'm receiving:

```
(env) jacob@jacob:~/EAGER/smili$ python
Python 3.7.10 (default, Feb 26 2021, 18:47:35)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from smili import imdata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jacob/EAGER/smili/smili/imdata/__init__.py", line 11, in <module>
    from .imdata import *
  File "/home/jacob/EAGER/smili/smili/imdata/imdata.py", line 33, in <module>
    from .. import fortlib, util, uvdata
ImportError: /home/jacob/EAGER/smili/smili/fortlib.so: undefined symbol: PyCObject_Type
>>>
```

**Comment by kazuakiyama** [comment]
Hi @jacobleonard545 

Sorry that I was late to get back to you. After seeing what you wrote in another issue thread, I suspect that there may be inconsistent version of f2py used to compile SMILI. Would you check if your f2py is coming from the numpy in your anaconda? If you use system-installed f2py (which can be installed by yum / apt-get, for instance), this may create a conflict with your local python environment from anaconda.

**Comment by jacobleonard545** [comment]
Hi @kazuakiyama 

Thank you for your time and responses, I was able to figure out the issue. I used pyenv to install the needed anaconda package and set it to global, but activating a virtual environment through conda seemed to mess things up. Once the environment is set up and following the documentation, it seems everything was installed properly!
