### ISSUE TITLE
f2py: not found

### ISSUE THREAD

**Issue by victorperezdiez** [astrosmili/smili#5]
Dear Kazu and SMILI developers

I'm trying to install SMILI, but I can't because f2py can't be found. Following the tutorial, when I do "./configure", it says:
"checking for f2py... no"

And after "make install":
/bin/sh: 1: f2py: not found
make[1]: * [makefile:136: fortlib.so] Error 127

I installed numpy with pip3, so I think that the issue should be related with the path to read f2py. My path to SMILI (and to lib/pkgconfig) is /home/vperez. My path to numpy is /home/vperez/.local/lib/python3.7/site-packages. My OS is Debian 10.

Any advice would be welcome. Thank you very much for your time

**Comment by jacobleonard545** [comment]
I had this issue as well and it's a quick fix. I'm on ubuntu and used this command to install f2py since it's a part of numpy now:

```sudo apt install python-numpy```

However, I believe I am still running into f2py related issues in later parts. Please let me know if this is incorrect.

**Comment by victorperezdiez** [comment]
Issue solved! Thank you very much

**Comment by kazuakiyama** [comment]
@victorperezdiez as already mentioned, f2py is a part of numpy. The path sounds to me that you have your own local python environment. As far as you installed numpy there, there should be the corresponding f2py in your python environment. I think you don't have a path to its f2py. The system package system (like apt, aptitude, yum) will install numpy only to the systsm's python environment. This would allow to use f2py, but I don't think it will guarantee that the compiled python module is workable in your local environment for instance if the version is significantly different.
